id: I90766D61
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T19:25:34+00:00'
last_modified: '2022-06-10T04:11:57.860790+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2DB25450
  title: ཨ་གློསསརཡ་ཨོཕ༹་ཐེ་ཏྲིབེས་ཨནད་ཅསྟེས་ཨོཕ༹་ཐེ་པུནཇབ་ཨནད་ནོརཐ-ཝེསཏ་ཕ༹ྲོནཏིཨེར་པྲོབི༹ནཅེ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4AF9:
      image_group_id: I1PD36343
      title: Volume 1 of a glossary of the tribes and castes of the punjab and north-west
        frontier province
      total_pages: 582
      order: 1
      base_file: 4AF9.txt
    '8038':
      image_group_id: I1PD36344
      title: Volume 2 of a glossary of the tribes and castes of the punjab and north-west
        frontier province
      total_pages: 542
      order: 2
      base_file: 8038.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
